server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Nuxt static files
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API proxy
    location /api/ {
        proxy_pass http://caretop-backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
